# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='author_id',
            new_name='author',
        ),
    ]
